# Output files/checkpoints will be stored with this run name folder structure.
# Ensure the model name is first part of the run, e.g. "vgg16-pneumonia-run1"

run_name: "vgg16-pneumonia-final2"

datadir: "/home/nishita/datasets/chest_xray"

# Choose from "vgg16" or "resnet50"
model: "vgg16"
gpus: "0"

# Each task will be run sequentially one after the other in the given order:
# Choose from: ["EDA", "train", "evaluate", "predict"]
tasks: ["train", "evaluate"]

train:
  batch_size: 8
  n_epochs: 20
  optimizer: "Adam"
  learning_rate: 1e-4

evaluate:
  batch_size: 8
  data_split: ['val', 'test'] #choose between 'train', 'val', 'test'

predict:
  image_path: "/home/nishita/datasets/chest_xray/train/PNEUMONIA/person1_bacteria_2.jpeg"







