run_name: "vgg16-pneumonia-run1"

datadir: "/home/nishita/datasets/chest_xray"

model: "vgg16"

plot: False

train:
  batch_size: 8
  n_epochs: 10

#evaluate:
#  img_path: "path/here"
#  num_images: -1
#  data_split: "val"




